AsyncTask
AnnaKlimchuk/Android-1C-2018 pull request #2
Opened 2018-10-26 13:45 UTC by AnnaKlimchuk

2018-10-27 20:22 UTC, IvanShafran commented
PersonDetailActivity и PersonDetailFragment имеют один и тот же код. Это плохо. Есть два решения:
1) PersonDetailActivity открывает внутри PersonDetailFragment
2) Вместо открытия PersonDetailActivity добавлять PersonDetailFragment на экран PersonListActivity поверх списка

2018-10-27 20:26 UTC, IvanShafran requested changes
В целом мне нравится всё. 
По коду стоит следить за видимостью полей. Многие поля можно сделать private. Но это мелочь.
Остальные комментарии тоже посмотри и поправь, пожалуйста

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/MyApplication.java
> +    public final void onCreate() {
final тут не очень понятно зачем

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/MyApplication.java
> +        PersonStorage.setInitialData();
Это хорошо

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/ViewsActivity.java
>      Button button, backButton;
Стоит по максимуму уменьшать видимость полей и других сущностей. Инкапсуляция рулит) Конкретно здесь надо добавить private для всех полей.

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/PersonStorage.java
> +    // TODO делать setInitialData один раз за всё приложение
Это уже делается, как понимаю

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/PersonStorage.java
>          persons.put(id, new Person(id, name, "", imageRes, "press to set birthday"));
private static final переменные обычно пишут таким образом: SOME_FIELD

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/PersonListActivity.java
>          new_fragment = new PersonListFragment();
В Java codeStyle немного другой: new_fragment -> newFragment

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/PersonListActivity.java
>      public void onBackPressed() {
Заметил баг. Если перейти в landscape режим. Тыкнуть на персонажа. Затем нажать назад, то будет пустой белый экран

2018-10-27 20:26 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/PersonListFragment.java
>          recyclerView.setLayoutManager(layoutManager);
recyclerView.setHasFixedSize(true); Такая штука ускоряет работу RecyclerView, если все элементы одинакового размера

2018-10-28 21:24 UTC, AnnaKlimchuk commented on app/src/main/java/com/example/anna/myapplication/PersonListActivity.java
>      public void onBackPressed() {
Это происходит из-за 5 секундной задержки при загрузке списка людей. Возможно, я неправильно поняла 5 задание :(

2018-10-29 10:57 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/PersonListActivity.java
>      public void onBackPressed() {
Переживать не надо. Представь себя со стороны пользователя. Чтобы ты ожидала там увидеть? Я бы ожидал, чтобы картинка профиля закрылась, а список остался. А во время второго нажатия назад уже и список закрылся

2018-10-29 10:59 UTC, IvanShafran approved these changes

2018-10-29 11:47 UTC, IvanShafran commented
Меня в целом всё устраивает. По поводу модификаторов protected и package private(когда ничего не написано) я придерживаюсь мнения, что их стоит избегать. protected стоит использовать при наследовании, а package-private для сокрытия сущностей вне пакета

2018-10-29 11:47 UTC, merged