usage of database with SQLite and Room
AnnaKlimchuk/Android-1C-2018 pull request #3
Opened 2018-11-06 02:58 UTC by AnnaKlimchuk

2018-11-08 20:01 UTC, IvanShafran commented
А в чём смысл использовать room, если таблица создается руками, запись в бд делается руками. Как-то потенциал room тут не очень раскрыт, мне кажется

2018-11-08 20:08 UTC, IvanShafran requested changes

2018-11-08 20:08 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/data/MySQLiteOpenHelper.java
> +public class MySQLiteOpenHelper extends SQLiteOpenHelper {
Название как-то не очень. Я бы предложил AppSqliteOpenHelper или подобное. My как-то больше для семплов кода используется

2018-11-08 20:08 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/data/MySQLiteOpenHelper.java
> +    public interface Columns extends BaseColumns {
Такие штуки лучше выносить в отдельный класс PersonContract, например. Вместе с названием таблицы

2018-11-08 20:08 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/data/MySQLiteOpenHelper.java
> +        dataBase.execSQL("DROP TABLE IF EXISTS " + TABLE_NAME);
При изменении базы данных удалять все пользовательские данные?) Какая-то странная логика.
Этот мето можно оставить пустым, если ты только создала бд

2018-11-08 20:08 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/data/PersonRepository.java
> +public class PersonRepository {
Этот класс нужно разбить на два. Один держит ссылку на базу данных, умеет открывать закрывать. (DatabaseHolder) Второй, использует первый для получения базы данных и выполнения с ней операций. (PersonRepository)

2018-11-08 20:08 UTC, IvanShafran commented on app/src/main/java/com/example/anna/myapplication/presentation/SQLiteDBActivity.java
> +            return "There are " + MyApplication.getRepository().loadAll().size() + " persons:\n" + MyApplication.getRepository().loadAll().toString();
Надо бы загрузку один раз вызывать вместо двух. Чтение из бд относительно долгая операция. Нужно завести переменную просто

2018-11-10 22:43 UTC, AnnaKlimchuk commented
> 
> 
> А в чём смысл использовать room, если таблица создается руками, запись в бд делается руками. Как-то потенциал room тут не очень раскрыт, мне кажется

Я хотела попробовать использование и Room и SQLite. В коде это две совершенно разные независимые реализации. 
Для Room - AddDatabase и PersonDao, для SQLite - AppSQLiteOpenHelper, DatabaseHolder и PersonRepository.
Сейчас приложение использует Room , а код для SQLite закомментирован.

2018-11-10 22:48 UTC, AnnaKlimchuk commented on app/src/main/java/com/example/anna/myapplication/data/MySQLiteOpenHelper.java
> +        dataBase.execSQL("DROP TABLE IF EXISTS " + TABLE_NAME);
Как я поняла, метод onUpgrade() вызывается при модификации данных. Этим кодом я хотела реализовать обновление таблицы.
Читала об этом здесь: http://developer.alexanderklimov.ru/android/sqlite/android-sqlite.php .

2018-11-10 23:23 UTC, IvanShafran approved these changes

2018-11-10 23:23 UTC, merged